### ISSUE TITLE
Z3 error on some inputs

### ISSUE THREAD

**Issue by joom** [joom/proof-tree-builder#15]
Trying to prove `i < n |- i + 1 <= n` with Z3 gives the error `pthread_create(&m_thread_id, NULL, &thread_func, this) == 0`.

Also mentioned in https://github.com/cpitclaudel/z3.wasm/issues/2.

**Comment by ViRb3** [comment]
There are now official bindings of z3 which support threads, so this use case should work. Check https://github.com/cpitclaudel/z3.wasm/issues/6.
